// internal/common/errors/codes.go
package errors

// Infrastructure
const (
	SUBSCRIPTION_INVALID       = "SUBSCRIPTION_INVALID"
	SUBSCRIPTION_EXPIRED       = "SUBSCRIPTION_EXPIRED"
	SUBSCRIPTION_CHECK_FAILED  = "SUBSCRIPTION_CHECK_FAILED"
	TEMPLATE_NOT_FOUND         = "TEMPLATE_NOT_FOUND"
	TEMPLATE_VALIDATION_FAILED = "TEMPLATE_VALIDATION_FAILED"
)

// Data Access
const (
	DATABASE_CONNECTION_FAILED      = "DATABASE_CONNECTION_FAILED"
	QUERY_EXECUTION_FAILED          = "QUERY_EXECUTION_FAILED"
	QUERY_TIMEOUT                   = "QUERY_TIMEOUT"
	INVALID_QUERY_TYPE              = "INVALID_QUERY_TYPE"
	ELASTICSEARCH_CONNECTION_FAILED = "ELASTICSEARCH_CONNECTION_FAILED"
	SEARCH_QUERY_FAILED             = "SEARCH_QUERY_FAILED"
	SEARCH_TIMEOUT                  = "SEARCH_TIMEOUT"
	INDEX_NOT_FOUND                 = "INDEX_NOT_FOUND"
)

// Business Logic
const (
	INVALID_FILTER_FORMAT         = "INVALID_FILTER_FORMAT"
	APPLICATION_VALIDATION_FAILED = "APPLICATION_VALIDATION_FAILED"
	DATABASE_INSERT_FAILED        = "DATABASE_INSERT_FAILED"
	DUPLICATE_APPLICATION         = "DUPLICATE_APPLICATION"
	NOTIFICATION_SEND_FAILED      = "NOTIFICATION_SEND_FAILED"
)

// AI/ML
const (
	INTENT_PARSING_FAILED = "INTENT_PARSING_FAILED"
	INTENT_API_TIMEOUT    = "INTENT_API_TIMEOUT"
	WEB_SEARCH_TIMEOUT    = "WEB_SEARCH_TIMEOUT"
	LLM_TIMEOUT           = "LLM_TIMEOUT"
	LLM_SYNTHESIS_FAILED  = "LLM_SYNTHESIS_FAILED"
)
