# configs/config.prod.yaml
app:
  environment: production

camunda:
  oauth:
    enabled: true
    client_id: "worker-client"
    client_secret: "AxgPPsstY5YDst15rDvfz64KsslQUorz"
    token_url: "https://dev-api.lemici.com/realms/camunda-platform/protocol/openid-connect/token"
    audience: "zeebe-api"

auth:
  keycloak:
    url: "https://dev-api.lemici.com"
    realm: "camunda-platform"
    issuer: "https://dev-api.lemici.com/realms/camunda-platform"
    clientId: "lemici-frontend"
    client_secret: "client-secret"
    admin_client_id: "worker-client"                     
    admin_client_secret: "AxgPPsstY5YDst15rDvfz64KsslQUorz"
    publicBaseUrl: "https://dev-api.lemici.com"
    redirectUrl: "https://dev-api.lemici.com/api/v1/auth/callback"
    post_login_redirect_uri: "https://lemici.com/"
    login_redirect_uri: "https://lemici.com/login"
    post_logout_redirect_uri: "https://lemici.com/"
    callback_redirect_uri: "https://lemici.com/"
integrations:
  smtp:
    host: "smtp-relay.brevo.com"
    port: 587
    username: "a8ea4d001@smtp-brevo.com"
    password: "b7KR9FO0hUXtcgNw"
    use_tls: true
    default_from: "noreply@lemici.com"

  internal: 
    operations_alert_email: "Operations@lemici.com"
    operations_alert_name: "Lemici Operations Team"
    marketing_alert_email: "marketing@lemici.com"
    marketing_alert_name: "Lemici Marketing Team"
