name: Backend + Camunda CI Pipeline

on:
  push:
    branches:
      - prod
      - mvp
      - demo

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  ci:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: go mod tidy

      - name: Build services
        run: go build ./...

      - name: Run tests
        continue-on-error: true
        run: |
          PKGS=$(go list ./... \
            | grep -v "/test/e2e" \
            | grep -v "/cmd/tools/registry-updater" \
            | grep -v "/internal/workers/auth/captcha-verify")

          go test $PKGS

      - name: Build Gateway image
        run: |
          docker build -t ${{ vars.BACKEND_GATEWAY_IMAGE }}:${{ github.sha }} \
            -f deployments/docker/Dockerfile.gateway \
            .

      - name: Build Worker image
        run: |
          docker build -t ${{ vars.BACKEND_WORKER_IMAGE }}:${{ github.sha }} \
            -f deployments/docker/Dockerfile.worker \
            .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag images for ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_URL="$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"

          docker tag ${{ vars.BACKEND_GATEWAY_IMAGE }}:${{ github.sha }} \
            $ECR_URL/${{ vars.BACKEND_GATEWAY_IMAGE }}:${{ github.sha }}

          docker tag ${{ vars.BACKEND_WORKER_IMAGE }}:${{ github.sha }} \
            $ECR_URL/${{ vars.BACKEND_WORKER_IMAGE }}:${{ github.sha }}

          docker tag ${{ vars.BACKEND_GATEWAY_IMAGE }}:${{ github.sha }} \
            $ECR_URL/${{ vars.BACKEND_GATEWAY_IMAGE }}:latest

          docker tag ${{ vars.BACKEND_WORKER_IMAGE }}:${{ github.sha }} \
            $ECR_URL/${{ vars.BACKEND_WORKER_IMAGE }}:latest

          echo "ECR_URL=$ECR_URL" >> $GITHUB_ENV

      - name: Push images to ECR
        run: |
          docker push $ECR_URL/${{ vars.BACKEND_GATEWAY_IMAGE }}:${{ github.sha }}
          docker push $ECR_URL/${{ vars.BACKEND_WORKER_IMAGE }}:${{ github.sha }}

          docker push $ECR_URL/${{ vars.BACKEND_GATEWAY_IMAGE }}:latest
          docker push $ECR_URL/${{ vars.BACKEND_WORKER_IMAGE }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/Workflow-and-Workers/deployments/docker

            ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            ECR_URL="$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"

            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin $ECR_URL

            echo "Pulling latest code..."
            git fetch --all
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}


            echo "Stopping existing containers..."
            docker compose down

            echo "Pulling latest images..."
            docker compose pull

            echo "Starting updated containers..."
            docker compose up -d --remove-orphans

            echo "Cleaning old Docker resources..."
            docker system prune -af

            echo "Deployment completed."
