name: Deploy Keycloak Theme

on:
  push:
    branches: [mvp]
    paths:
      - 'keycloak-theme/**'

permissions:
  id-token: write
  contents: read
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Print OIDC subject
        run: |
         echo "Requesting token..."
         TOKEN=$(curl -s "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
         -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')

         echo $TOKEN | cut -d "." -f2 | base64 -d
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY_DEV }}
          script: |
            cd ~/Workflow-and-Workers
            echo "Pulling latest code..."
            git pull origin mvp

            cd deployments/docker
            echo "Recreating Keycloak..."
            docker compose up -d keycloak
            echo "Done"
